# Generated by Django 5.1.1 on 2024-11-23 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategoryDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(default='Standard', max_length=100)),
                ('room_photo', models.ImageField(blank=True, default='lizard.jpeg', null=True, upload_to='')),
                ('room_desc', models.TextField(blank=True, max_length=200)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=' ', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.roomcategorydashboard')),
            ],
        ),
    ]
