# Generated by Django 5.1.3 on 2024-11-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0)),
                ('room_photo', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('room_type', models.CharField(max_length=30)),
                ('room_desc', models.TextField(blank=True, max_length=200)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.roomcategory')),
            ],
        ),
    ]
