# Generated by Django 5.1.3 on 2024-11-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='category_id',
            field=models.CharField(default='Standard', max_length=100),
        ),
    ]
