# Generated by Django 5.1.4 on 2024-12-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_roomcategory_room_room_photo_alter_room_room_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_photo',
        ),
    ]
