# Generated by Django 5.1.3 on 2024-11-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_room_room_id_alter_roomcategory_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='rooms_available',
        ),
    ]
