# Generated by Django 5.1.3 on 2024-11-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_roomcategory_rooms_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='room_type',
        ),
    ]
