# Generated by Django 5.1.4 on 2024-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_room_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
