# Generated by Django 5.1.3 on 2024-11-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_roomcategory_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='room_photo',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='media'),
        ),
    ]
