# Generated by Django 5.1.4 on 2024-12-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_room_is_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_reserved',
        ),
    ]
