# Generated by Django 5.1.3 on 2024-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_roomcategory_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos/'),
        ),
    ]
