# Generated by Django 5.1.1 on 2024-10-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_fname_remove_customuser_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to=''),
        ),
    ]
