# Generated by Django 5.1.1 on 2024-09-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortingroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_photo',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
