# Generated by Django 5.1.1 on 2024-11-26 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_roomcategory_room_room_photo_alter_room_room_id_and_more'),
        ('sortingroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_category',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room'),
        ),
        migrations.DeleteModel(
            name='RoomCategory',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
