# Generated by Django 5.1.1 on 2024-09-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortingroom', '0002_alter_room_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rooms_available',
            field=models.IntegerField(default=0),
        ),
    ]
