# Generated by Django 5.1.1 on 2024-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortingroom', '0003_room_rooms_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
