# Generated by Django 5.1.1 on 2024-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortingroom', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
