# Generated by Django 5.1.1 on 2024-11-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortingroom', '0013_alter_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_check_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sortingroom.room'),
        ),
    ]
