# Generated by Django 5.1.1 on 2024-11-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortingroom', '0015_alter_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
